package com.edm;

import java.awt.List;
import java.util.ArrayList;

import javax.swing.event.ListSelectionEvent;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import model.*;
import repository.*;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/edm") // This means URL's start with /edm (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository           // Which is auto-generated by Spring, we will use it to handle the data
	private falCourseRepo FC;
	

	@GetMapping(path="/all")
	public @ResponseBody Iterable<faculty_course> getAllUsers() {
		// This returns a JSON or XML with the users
		return FC.findAll();
	}
	
}
